# Generated by Django 3.1.2 on 2020-11-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
                ('ship_type', models.CharField(max_length=50)),
                ('points', models.CharField(max_length=50)),
                ('faction', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('commander', models.BooleanField(default=False)),
                ('officer_1', models.BooleanField(default=False)),
                ('officer_2', models.BooleanField(default=False)),
                ('officer_3', models.BooleanField(default=False)),
                ('officer_4', models.BooleanField(default=False)),
                ('fleet_command_1', models.BooleanField(default=False)),
                ('fleet_command_2', models.BooleanField(default=False)),
                ('fleet_command_3', models.BooleanField(default=False)),
                ('fleet_command_4', models.BooleanField(default=False)),
                ('offensive_retrofit_1', models.BooleanField(default=False)),
                ('offensive_retrofit_2', models.BooleanField(default=False)),
                ('defensive_retrofit_1', models.BooleanField(default=False)),
                ('defensive_retrofit_2', models.BooleanField(default=False)),
                ('turbolasers_1', models.BooleanField(default=False)),
                ('turbolasers_2', models.BooleanField(default=False)),
                ('ion_cannons_1', models.BooleanField(default=False)),
                ('ion_cannons_2', models.BooleanField(default=False)),
                ('ordinance_1', models.BooleanField(default=False)),
                ('ordinance_2', models.BooleanField(default=False)),
                ('support_team_1', models.BooleanField(default=False)),
                ('support_team_2', models.BooleanField(default=False)),
                ('weapons_team_1', models.BooleanField(default=False)),
                ('weapons_team_2', models.BooleanField(default=False)),
                ('experimental_retrofit_1', models.BooleanField(default=False)),
                ('experimental_retrofit_2', models.BooleanField(default=False)),
                ('super_weapon', models.BooleanField(default=False)),
                ('upgrade_title', models.BooleanField(default=False)),
            ],
        ),
    ]
