# Generated by Django 3.1.2 on 2020-11-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='points',
            field=models.IntegerField(max_length=50),
        ),
    ]
