# Generated by Django 3.1.2 on 2020-11-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0003_auto_20201117_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('objective_type', models.CharField(max_length=50)),
                ('setup', models.TextField()),
                ('special_rule', models.TextField()),
                ('end_of_round', models.TextField()),
                ('end_of_game', models.TextField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Squadron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
                ('squad_type', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('faction', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=50)),
                ('unique', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('upgrade_type', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('faction', models.CharField(max_length=50)),
                ('unique', models.BooleanField(default=False)),
                ('ship', models.CharField(max_length=50)),
                ('ships', models.CharField(max_length=50)),
                ('dual', models.CharField(max_length=50)),
                ('modification', models.BooleanField(default=False)),
            ],
        ),
    ]
