# Generated by Django 3.1.2 on 2020-11-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0004_objective_squadron_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
