# Generated by Django 3.1.2 on 2020-11-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0006_auto_20201118_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='end_of_game',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='end_of_round',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='setup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='special_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
