# Generated by Django 3.1.2 on 2020-11-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0007_auto_20201118_0354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ship',
            new_name='BaseShip',
        ),
    ]
