# Generated by Django 3.1.2 on 2020-11-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0009_ship'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_name', models.CharField(max_length=50)),
                ('fleet', models.ManyToManyField(related_name='fleet', to='armada.Ship')),
                ('objectives', models.ManyToManyField(related_name='fleet', to='armada.Objective')),
                ('squadrons', models.ManyToManyField(related_name='fleet', to='armada.Squadron')),
            ],
        ),
    ]
