# Generated by Django 3.1.2 on 2020-11-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0010_savedlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedLists',
            new_name='SavedList',
        ),
    ]
