# Generated by Django 3.1.2 on 2020-11-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0011_auto_20201119_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
