# Generated by Django 3.1.2 on 2020-11-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0012_ship_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_type', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
    ]
