# Generated by Django 3.1.2 on 2020-12-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armada', '0013_upgradeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseship',
            name='fleet_support_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseship',
            name='fleet_support_2',
            field=models.BooleanField(default=False),
        ),
    ]
